- CHANGELOG.md
- package.json
Fixes issues with a missing `regeneratorRuntime`.
>  Added babel runtime

- CHANGELOG.md
- package.json
- src/index.js
- src/reactors.js
- src/serialize.js
- src/types.js
- test/index.js
- test/mobx.js
- test/mocks.js
* Fix serialization to never include contexts
* Fix onResult not to be called if there was no context response
* Default validation function is now stubTrue
* Added internal mocks utility
> Small fixes

- CHANGELOG.md
- package.json
- src/index.js
Code that relies on webpack doesn't have access to the exampleTypes unless we export them.
> Exporting the exampleTypes

- CHANGELOG.md
- package.json
- src/index.js
- test/mobx.js
- test/mocks.js
Deprecate wrapping responses in `data`, will be removed in 3.0
> Deprecate wrapping responses in `data`, will be removed in 3.0

- CHANGELOG.md
- README.md
- package.json
- src/index.js
* Expose `mockService` as a top level export
> [2.7] Expose `mockService` as a top level export

- CHANGELOG.md
- README.md
- package.json
- src/actions.js
- src/index.js
- src/node.js
- src/reactors.js
- src/serialize.js
- src/traversals.js
- src/util/promise.js
- src/util/tree.js
- test/index.js
- test/mobx.js
Add `updatingPromise` to nodes which can be used to await nodes being updated (planned for subquery/cascade use case)
> Updating promise

- CHANGELOG.md
- package.json
- src/index.js
- src/mockService.js
- test/mobx.js
* Catch case where unsolicited node responses from the service for nodes that have never been updated explode because of missing upatingPromise (but still log in debug mode)
* Update mobx tests to use mobx 5
> Fix unsolicited responses exploding

- CHANGELOG.md
- package.json
- src/index.js
- test/index.js
* Fix bug preventing nodes without contexts from being marked as no longer updating.
> Mark when contextless nodes stop updating

- CHANGELOG.md
- package.json
* Republish 2.13.5 which was published manually without building.
> bump to 2.13.6 because of botched publish

- CHANGELOG.md
- package.json
- src/reactors.js
- src/traversals.js
- test/mobx.js
Children can be Observable Arrays, which are different from normal arrays (as far as MobX 4 can tell). This becomes an issue on MobX, specially when changing a group from having a `not` join property to any other value. For that reason, we're slicing them.
> Slicing children in our reactors

- CHANGELOG.md
- package.json
- src/exampleTypes.js
Add geo validate function just like we have it on the server side implementation for ES
https://github.com/smartprocure/contexture-elasticsearch/blob/master/src/example-types/geo.js#L48-L53
> validate for geo example type

- CHANGELOG.md
- package.json
- src/index.js
Fixed deep bug: afterSearch should be called at the moment we
receive new values. This would cause nodes previously marked for
update to not call afterSearch because these nodes weren't marked by
the current dispatch.
> Fixed deep bug

- CHANGELOG.md
- package.json
- src/exampleTypes.js
Add missing defaults for `subquery` and `savedSearch` example types.
> Add missing defaults for `subquery` and `savedSearch` example types.

- CHANGELOG.md
- package.json
- src/exampleTypes.js
The `mongoId` mongo example type allows for its value to be set in either the `values` or the `value` fields, however, we only ran reactors on mutations to the `values` field. This PR fixes it so we also run reactors on mutations to `value`.
> Add value reactor for mongoId example type

- CHANGELOG.md
- README.md
- package.json
- src/actions.js
The action is just a mutate with default values from the node type definition (save for the `field` property). It seemed easier to do it this way instead of adding a new property in the node's type definition to include/exclude properties to reset to their default values.
> Add clear action to reset a node's value to its defaults

- CHANGELOG.md
- package.json
- src/node.js
The line between what to serialize and not serialize is blurry and it
depends on the requirements of a specific application. It turns out we
require to maintain this state in a client of the library.
A more useful approach would be to parametrize the fields to serialize,
but this will do for now.
> Serialize a node's paused field

- CHANGELOG.md
- package.json
- src/actions/index.js
- test/index.js
Fix bug with replace not inserting at the right index with mobx
> Fix bug with replace not inserting at the right index with mobx

- CHANGELOG.md
- package.json
- src/actions/index.js
- src/reactors.js
- test/mobx.js
The first step in factoring out contexture-react's [ContextureClientBridge](https://github.com/smartprocure/contexture-react/blob/master/src/queryBuilder/QueryBuilder.js). To avoid any funny business, we convert node paths that are MobX ObservableArrays (as is the case in contexture-react) to regular arrays before using them in tree operations. Right now, that's done inside ContextureClientBridge in contexture-react; this PR moves it into contexture-client instead.
We're currently using `Array.slice()` for this exact purpose elsewhere within contexture-client (smartprocure/contexture-client#74). It seems that `_.toArray` is better anyway (smartprocure/contexture-react#120), so for consistency, I also changed the existing occurrences of `slice` to `_.toArray`.
> Add _.toArray to actions

- CHANGELOG.md
- README.md
- package.json
- src/actions/index.js
- test/index.js
Closes #106
The test diff looks worse than it actually is; the old `replace` assertions are still there, just changed to `criteria2` so I could add the new ones above them as `criteria1`.
> Add transform function support to `replace`

- CHANGELOG.md
- package.json
- src/index.js
- src/traversals.js
- test/index.js
On service error we raise the `onError` but leave the tree post `prepForUpdate` as is with all the `updating` flags being set to true. We reset them via `resetUpdate` to be back to normal post service exception. This way the UI should automatically reset as well.
> Adding processResponse so we can continue

- CHANGELOG.md
- package.json
- src/subquery.js
- test/index.js
In regards to https://github.com/smartprocure/bid-search/issues/3500
In the case where the source tree has no values we should not `mutate` but `clear` the target node.
> Handle the empty values better with subquery

- CHANGELOG.md
- README.md
- package.json
- src/index.js
- test/mobx.js
In the mobx case, if you try to make a contexture tree observable, the client won't see the changes. The underlying issue is documented in this runkit: https://runkit.com/daedalus28/mobx-reference-issues
However, changing `disableAutoUpdate` should be able to be observed in the mobx scenario. All we need to do to remedy this is make sure that we init the returned `TreeInstance` with `initObject` (provided by the `mobxAdapter` as config) so that the client retains the observable instance.
Complete with unit tests and everything 😄 Fun fact - with this PR we now have *100* test cases in `contecxture-client` 🎉
> Observe Tree Instance

- CHANGELOG.md
- README.md
- package.json
- src/index.js
- src/util/tree.js
- test/index.js
Add `processResponseNode` to support intermediate partial results from the server
> Process Intermediate Server Results

- CHANGELOG.md
- package.json
- src/subquery.js
Fixes #121 
* clear unlike mutate returns a promise when given one argument -- just need to return a function that calls that
> feature/121 - fix subquery afterSearch

- CHANGELOG.md
- package-lock.json
- package.json
- src/exampleTypes.js
- Adding the entry for the `dateRangeFacet`
in regards to https://github.com/smartprocure/spark/issues/6298
> Add the `dateRangeFacet`

- CHANGELOG.md
- package-lock.json
- package.json
- src/exampleTypes.js
Fixes #142 
* We need to get fresh results if `tags` or `exact` are changed now that the results will be counts by individual tag (https://github.com/smartprocure/contexture-elasticsearch/pull/163). `join` itself doesn't require a fresh calculation of results because it doesn't matter for the count on a single tag so that can stay `others`
> Feature/142 - update tagsQuery context reactors

- CHANGELOG.md
- package-lock.json
- package.json
- src/exampleTypes.js
- Default the range the actual default value of `exact`.
> Default date type range to `exact`

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.js
- src/reactors.js
Resolves #134 
* Refactoring to simplify code (preparing for larger updates)
* Also fixes a bug when the `standardChange` reactor should return `all`, but wouldn't have
> Refactoring

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.js
- src/serialize.js
- test/index.js
Immediate updates are now debounced 10ms (which happens on self affecting reactors when disableAutoUpdate is true).
This should fix the issue where the tagsQuery component dispatches tons of mutates when pasting a large number of tags (which all triggerImmediate because they have self affecting reactors)
> Debounce immediate updates

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.js
- src/subquery.js
- test/index.js
* Debounce for immediate updates is removed
* Fixing logic `filterOnly` flag for serialized tree
* Subquery: making the whole target tree to await for source node
> Fixes: filterOnly for serialized tree, awaiting logic for subquery

- CHANGELOG.md
- package-lock.json
- package.json
- src/exampleTypes.js
- src/index.js
- src/node.js
- test/index.js
* Per type response merges via `shouldMergeResponse` and `mergeResponse`- allows types to retain the response state between search calls to cleanly support things like inifinite scrolling and drilldowns. Will automatically always force response replacement when updated by others (since the query has likely changed, invalidating prior responses). This is tracked by a new `forceReplaceResponse` internal state flag per node.
* Leverages response merge feature to implement `infiniteScroll` for `results` (just set `infiniteScroll` to true and `mutate` increments to `page`!)
* Fix: Always `_.deepClone` defaults on node init to prevent accidentally mutating type defaults
* Cleanup: swap custom mutable mergeWith with extend
* Cleanup: remove references to results.context.response (since we no …
> ResponseMerges

- CHANGELOG.md
- package-lock.json
- package.json
- src/actions/index.js
- src/exampleTypes.js
- src/index.js
- src/node.js
- src/reactors.js
- src/traversals.js
- src/types.js
- src/util/futil.js
- src/util/promise.js
- src/util/tree.js
- test/_mobx.js
- test/index.js
* Better `pivot` `mergeResponse` implementation that merges groups by key
* Move from `futil-js` to `futil`
Closes #162
> Better pivot merges

- CHANGELOG.md
- package-lock.json
- package.json
- src/actions/index.js
- src/index.js
- src/node.js
- test/index.js
Fix: Use `snapshot` on `typeDefaults` instead of `_.deepClone` to fix regression from `2.38.0` for real world apps that end up with observable `typeDefaults`
This really shouldn't be a thing, but it's reasonable since the premise of `mobx` utilization at the moment is to just have everything observable. This hastens #169 since we can drastically simplify things by just expose observability from the client and obviating the need for mobx (even in apps using it already).
Note: for anyone using the undocumented `initNode` method directly, this would be a breaking change since `initNode` now takes an object of `{ extend, types, snapshot }` instead of `extend` and `types` as the first two curried arguments. This would only affect users of the experimental `addActions` API, of which there are …
> Snapshot type defaults

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/exampleTypes.js
- src/index.js
- src/listeners.js
- src/util/futil.js
- test/index.js
Add `watchNode` API. Can be used to create a native react hook, dependency-free!
Here's a quick sketch:
```js
let useNode = (path, tree, keys = []) => {
let [lastUpdate, setLastUpdate] = React.useState(new Date())
useEffect(() => tree.watchNode(path, () => setLastUpdate(new Date()), keys))
return tree.getNode(path)
}
```
then later:
```js
let NodeBlob = ({ tree, path }) => {
let node = useNode(path, tree)
return <pre>{JSON.stringify(node, 0, 2)}</pre>
}
```
or:
```js
let NodeBlob = ({ tree, path }) => {
let node = useNode(path, tree, ['value', 'context'])
return <pre>{JSON.stringify(node, 0, 2)}</pre>
}
```
> Watch Node

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/actions/index.js
- src/actions/wrap.js
- src/index.js
- src/listeners.js
- src/mockService.js
- src/node.js
- src/serialize.js
- src/traversals.js
- src/types.js
- src/util/futil.js
- src/util/tree.js
- test/_mobx.js
- test/index.js
- test/listeners.js
Removes internal dependency on the flat tree representation. Fixes #131.
Before merging, we should have an answer for #90 so that we can eliminate the only known external (albeit undocumented) use of the flat tree so we can rip it out entirely.
TODO: we might want to `_.memoize` `getNode` and clear the cache in mutating actions. That would preserve the flat tree's performance, but might not be worth the complexity.
> Deprecate flat tree

- CHANGELOG.md
- package.json
- src/exampleTypes.js
> Pivot node: deprecating subtotals

- .github/workflows/pull-request.yaml
- .github/workflows/push-master.yaml
- CHANGELOG.md
- package-lock.json
- package.json
- src/exampleTypes.js
Resetting the drilldown when the pivot node or tree is changed allows to return expected root results instead of nested drilldown results.
EX: criteria filters didn't work properly when drilldown was applied or changing the columns or rows config was not returning the new results
> fix: reset the drilldown on tree mutations

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.js
- src/serialize.js
- test/index.js
New feature: new per-node hook `onSerialize` allows users to customize tree nodes as the tree is being serialized.
> Add per-node onSerialize hook

- CHANGELOG.md
- package-lock.json
- package.json
- src/exampleTypes/pivot.js
- Add new field `selectedRows`. Modify/Clear as needed `selectedRows` when the `expansions` array and/or query results are changing
> Pivot node changes to support selectedRows recompute

- CHANGELOG.md
- package-lock.json
- package.json
- src/exampleTypes/pivot.js
when checking which selected rows should remain
> Do not remove root node when present in `selectedRows`

- CHANGELOG.md
- package.json
We're importing from `dist` in quite a few places (which we shouldn't do) and the files do not get resolved by node because of the `exports` field. Proper fix is to re-export everything we need.
> Revert package.json exports field

- CHANGELOG.md
- package.json
This is what nodejs uses to decide which files of the package to use (https://nodejs.org/api/packages.html#subpath-exports). Now any of these will work in the node repl! 🤯 
```javascript
let cjs_client = require('contexture-client')
let esm_client = await import('contexture-client')
let cjs_pivot = require('contexture-client/exampleTypes/pivot.js')
let esm_pivot = await import('contexture-client/exampleTypes/pivot.js')
```
> Add exports field to package.json

- CHANGELOG.md
- package.json
- scripts/build.js
- yarn.lock
When an ESM package is transpiled to CJS, default exports are wrapped in `default`, g.g. `export default foo` will need to be imported as `let foo = require('library').default` instead of `let foo = require('library')`.
This is very annoying as I don't want to change all our default exports to be named (although we should do this anyway to avoid these kinds of issues). In the meantime, we can work around this by using https://github.com/flex-development/toggle-pkg-type#when-should-i-use-this, which is specific to esbuild.
Here's a more detailed explanation on the issue: https://esbuild.github.io/content-types/#default-interop
> Attempt to fix default exports
