smartprocure/contexture-client

CHANGELOG.md, package.json, src/util/tree.js
Otherwise it's setting incomplete path for children at valdiation.
=> flattenTree fix for nodes that already have a path

test/validation.js
Proof that #6 fixes a real bug :D
There might be other ways to fix this. This is just one way of doing so :)
=> validateGroup flattenTree test for #6

README.md
=> Document features

CHANGELOG.md, README.md, package.json
=> First pass at some real documentation

CHANGELOG.md, package.json, src/index.js, src/reactors.js, test/index.js, test/mobx.js
=> v2.0.3 with fixes for nested custom reactors and mergeOn with arrays

.gitignore, CHANGELOG.md, package.json, src/exampleTypes.js
Types based on real life use cases.
=> Some example types

CHANGELOG.md, package.json, src/exampleTypes.js
We should never do something like this!
=> Removed the group reactor

CHANGELOG.md, package.json, src/actions.js, test/index.js
=> Refresh Action

CHANGELOG.md, README.md, package.json
=> 2.2.1 onChange comment at the README

CHANGELOG.md, package.json, src/actions.js, src/index.js, test/index.js, test/mobx.js
=> Curried mutate and a default debounce

CHANGELOG.md, README.md, package.json, src/exampleTypes.js, src/node.js, test/index.js, test/mobx.js
More Example Types and `defaults` sugar
=> More Example Types and `defaults` sugar

CHANGELOG.md, package.json, src/index.js
Account for core returning an empty data object
=> Account for core returning an empty data object

CHANGELOG.md, package.json, src/exampleTypes.js, src/reactors.js, test/index.js, test/mobx.js
Update Example Type Defaults and Reactors
=> Update Example Type Defaults and Reactors

CHANGELOG.md, package.json, src/mockService.js, test/index.js
Ensure mockService is accessible from `src`
=> Ensure mockService is accessible from `src`

CHANGELOG.md, package.json, src/exampleTypes.js
* Add missing example type defaults
=> Enhance example types

CHANGELOG.md, package.json, src/exampleTypes.js
=> More exampleTypes

CHANGELOG.md, README.md, package.json, src/actions.js, src/index.js, src/reactors.js, test/index.js
This is the "search button"
* Added `disableAutoUpdate` and `triggerUpdate` action
=> Disable auto search

CHANGELOG.md, package.json, src/exampleTypes.js
=> add tagsQuery example type

CHANGELOG.md, package.json, src/exampleTypes.js
And added subquery.useValues to mongoId
=> subquery needs to be lowercase

CHANGELOG.md, package.json, src/index.js, test/index.js, test/mobx.js
=> Fix for mobx 4

CHANGELOG.md, package.json, src/exampleTypes.js
Add key_value reactor for self on twoLevelMatch type
=> Add key_value reactor for self on twoLevelMatch type

CHANGELOG.md, package.json, src/exampleTypes.js, test/index.js
subquery support for terms_stats
=> Add getValues to terms_stats for subquery

CHANGELOG.md, package.json, src/exampleTypes.js
Add defaults and more reactors for geo type
=> Add defaults and more reactors for geo type

CHANGELOG.md, package.json, src/index.js
call the afterSearch hook only when an update has triggerred
=> Fix issue with afterSearch hook being called before an update has triggered

CHANGELOG.md, package.json, src/exampleTypes.js, test/index.js, test/mobx.js
=> Facet should have mode include by default

CHANGELOG.md, package.json, src/exampleTypes.js
findBestRange reactor for number type.
=> findBestRange reactor for number type.

CHANGELOG.md, package.json, src/exampleTypes.js
=> Self reactor on terms_stats filter property

CHANGELOG.md, package.json, src/exampleTypes.js
=> Default filter prop on terms_stats

CHANGELOG.md, package.json, src/exampleTypes.js
=> add multitext reactors

CHANGELOG.md, package.json, src/exampleTypes.js
* Add `subquery` and `savedSearch` example types.
=> Add `subquery` and `savedSearch` example types.

CHANGELOG.md, package.json, src/exampleTypes.js
Fixes #101 
sets defaults for geo location and radius
=> feature/101 - set defaults for geo location and radius

CHANGELOG.md, package.json, src/exampleTypes.js, src/index.js
Needed for https://github.com/smartprocure/contexture-react/pull/268
=> Add some type labels and expose more stuff on tree instance

CHANGELOG.md, package.json, test/index.js
Tests for the `clear` tree action.
=> Add clear action tests

CHANGELOG.md, package.json, src/index.js
This PR proposes to fix a udpated -> updated typo found in a log.
=> Fix log udpated -> updated typo

.gitignore, CHANGELOG.md, package-lock.json, package.json, src/exampleTypes.js
=> fix: tagsQuery validation

CHANGELOG.md, package-lock.json, package.json, src/exampleTypes.js
- `validate` expects a function
In regards to https://github.com/smartprocure/bid-search/issues/5086
=> Fix validateValueExistence

CHANGELOG.md, package-lock.json, package.json, src/exampleTypes.js
Handle new date type behavior in https://github.com/smartprocure/contexture-react/pull/405
=> Handle new date type behavior.

CHANGELOG.md, README.md, package-lock.json, package.json, src/serialize.js, test/index.js
This PR removes the marking and subsequent deletion of nodes with no value during tree serialization.
=> feat: remove mark for deletion logic

CHANGELOG.md, package-lock.json, package.json, src/exampleTypes.js
=> feature/137 - modify subquery reactors

CHANGELOG.md, package-lock.json, package.json, src/exampleTypes.js
Fixes #142 
* sets a default for the new context.results prop.
=> feature/142 - set default

.circleci/config.yml, CHANGELOG.md, package-lock.json, package.json, src/index.js, src/traversals.js, test/index.js
First take on self affecting dispatches updating only themselves when disabling auto update. Makes `triggerUpdate` optionally take a `path`.
=> Single Node Updates

CHANGELOG.md, package-lock.json, package.json, src/exampleTypes.js
=> Add pivot type

.github/workflows/pull-request.yaml, CHANGELOG.md, package-lock.json, package.json
=> ci: update pull-request test failure case

CHANGELOG.md, package.json, src/exampleTypes.js
Adding validation to a pivot type node, so we don't send empty ranges query to ES
=> [feature] Pivot node validation

CHANGELOG.md, package.json, src/exampleTypes.js
=> Pivot node: support for columns

CHANGELOG.md, package.json, src/exampleTypes.js
=> example column handling

CHANGELOG.md, package.json, src/exampleTypes.js, src/util/futil.js, test/index.js
=> Fix: Pivot node: deep merge for groups and columns

CHANGELOG.md, package.json, src/exampleTypes.js, test/index.js
=> [fix] Pivot node: response object merging

CHANGELOG.md, package-lock.json, package.json, src/exampleTypes.js, test/index.js
[GS-2204](https://govspend.atlassian.net/browse/GS-2204)
=> Feature: pivot pagination

CHANGELOG.md, package-lock.json, package.json, src/exampleTypes/pivot.js, test/index.js
=> fix(pivot): sorting and results merging

CHANGELOG.md, package-lock.json, package.json, src/exampleTypes/pivot.js
Do not reset expansions when the filters are changed
=> Do not reset expansions when the filters are changed

CHANGELOG.md, README.md, dangerfile.js, package.json, src/actions/index.js, src/actions/wrap.js, src/exampleTypes.js, src/exampleTypes/pivot.js, src/index.js, src/lens.js, src/listeners.js, src/mockService.js, src/node.js, src/reactors.js, src/serialize.js, src/subquery.js, src/traversals.js, src/util/futil.js, src/util/promise.js, src/util/tree.js, test/index.js, test/listeners.js
=> Format everything with prettier
